//MOVIES TYPES
export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';
export const FETCH_MOVIES_FAILED = 'FETCH_MOVIES_FAILED';
export const FETCH_MOVIES_REFRESH = 'FETCH_MOVIES_REFRESH';
export const FETCH_MOVIES_PAGINATE = 'FETCH_MOVIES_PAGINATE';
export const FETCH_MOVIES_STARTED = 'FETCH_MOVIES_STARTED';
export const MOVIES_CHANGE_PROPS = 'MOVIES_CHANGE_PROPS';


//MOVIES_DETAILS_REDUCER

